repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        additional_dependencies: ["black[jupyter]"]
        language_version: python3
        files: \.(py|ipynb)$
